Adds notes and TODOs while looking through librarian-notify-send script.

diff --git a/librarian-notify-send b/librarian-notify-send
--- a/librarian-notify-send
+++ b/librarian-notify-send
@@ -4,28 +4,42 @@
 # This file is a modified version of alt-notify-send. It has been modified to send images with the notifications
 # See:http://xbmc.org/wiki/?title=MythicalLibrarian#GNOME_Desktop_Notifications for usage
 
-user=`whoami`
-pids=`pgrep -u $user gnome-session`
+#TODO: Categories, from http://www.galago-project.org/specs/notification/0.9/x211.html
+# "transfer"   A generic file transfer or download notification that doesn't fit into any other category.
+# "transfer.complete"     A file transfer or download complete notification.
+# "transfer.error"        A file transfer or download error.
+# "network"  A generic network notification that doesn't fit into any other category.
+# "network.connected"     A network connection notification, such as successful sign-on to a network service. This should not be confused with device.added for new network devices.
+# "network.disconnected"  A network disconnected notification. This should not be confused with device.removed for disconnected network devices.
+# "network.error" A network-related or connection-related error. 
+
+user=$(whoami)
+pids=$(pgrep -u $user gnome-session)
 title=$1
 text=$2
 image=$3
 
 if [ -z "$title" ]; then
-        echo You need to give me a title >&2
-        exit 1
+  printf '%s\n' 'You need to give me a title' >&2
+  exit 1
 fi
+
 if [ -z "$text" ]; then
-        text=$title
+  text=$title
 fi
+
+#TODO: this isn't used... #NOTE: Ubuntu's Notify OSD and GNOME Shell both ignore this parameter.
 if [ -z "$timeout" ]; then
-        timeout=60000
+  #timeout=6000    #6 seconds
+  #timeout=60000   #1 minute
+  #timeout=180000  #3 minutes
+  timeout=1800000 #30 minutes
 fi
 
 for pid in $pids; do
-        # find DBUS session bus for this session
-        DBUS_SESSION_BUS_ADDRESS=`grep -z DBUS_SESSION_BUS_ADDRESS \
-                /proc/$pid/environ | sed -e 's/DBUS_SESSION_BUS_ADDRESS=//'`
-        # send message to DBUS
-        DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS \
-        notify-send -u low -i "$image" "$title" "$text"
+  # find DBUS session bus for this session
+  DBUS_SESSION_BUS_ADDRESS=$(grep -z DBUS_SESSION_BUS_ADDRESS /proc/$pid/environ | sed -e 's/DBUS_SESSION_BUS_ADDRESS=//')
+  # send message to DBUS
+  DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS notify-send -u low -i "$image" "$title" "$text"
+  #DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS notify-send --app-name=Kodi -t $timeout -u low -i "$image" "$title" "$text"
 done
