Fixes while testing:
  + Improve checks and debug messaging from get_tvdb_token().
  + Fixes series-status debug messages in download_series_identification().

diff --git a/myth2kodi b/myth2kodi
--- a/myth2kodi
+++ b/myth2kodi
@@ -868,7 +868,7 @@ m2k_init(){
   #Make sure our series list is consistent (directories still present).
   prune_series_list
 
-  [[ "$ONLINE_LOOKUP" != 'Disabled' ]] && get_tvdb_token
+  [[ "$ONLINE_LOOKUP" != 'Disabled' ]] && get_tvdb_token #TODO: if ! get_tvdb_token; then return 1; fi
 
   debug "myth2kodi script initialisation complete."
   debug "Running myth2kodi as '$CALLER'"
@@ -2650,7 +2650,7 @@ get_tvdb_token(){
 
   current_time="$(date +%s)"
   if [[ -f "$m2kdir/tvdb_token.json" ]]; then
-    token_last_updated="$(jq -r .updated "$m2kdir/tvdb_token.json")"
+    token_last_updated="$(jq -r '.updated' "$m2kdir/tvdb_token.json")"
     debug "Token last updated: '$(date --date="@$token_last_updated")'"
   else
     debug 'We do not have an existing token.'
@@ -2665,26 +2665,39 @@ get_tvdb_token(){
     curlPOST="curl -s -m '$Timeout' -X POST --header 'Content-Type: application/json' -H 'Accept: application/json' -d"
     data=\'"{\"apikey\": \"$APIkey\"}"\'
     token_json="$(eval "$curlPOST $data 'https://api.thetvdb.com/login'")"
-  elif (( (current_time - token_last_updated)/3600 > 12 )); then
-    debug 'Getting refreshed token using our current one.'
-    #Get a refreshed token using our currently valid token (if current is older than 12 hours).
+    if jq -e 'has("Error")' <<< "$token_json" > /dev/null; then
+      err "${FUNCNAME[0]}(): An error was returned by TheTVDB when attempting to GET a new a token."
+      return 1
+    fi
+  elif (( (current_time - token_last_updated)/3600 > 16 )); then
+    debug 'Getting refreshed token using our current one:'
+    ((LOGLEVEL > 3)) && debugcont "$TVDB_TOKEN"
+    #Get a refreshed token using our currently valid token (if current is older than 16 hours).
     curlGET="curl -s -m '$Timeout' -X GET --header 'Authorization: Bearer $TVDB_TOKEN' -H 'Accept: application/json'"
     token_json="$(eval "$curlGET 'https://api.thetvdb.com/refresh_token'")"
+    if jq -e 'has("Error")' <<< "$token_json" > /dev/null; then
+      err "${FUNCNAME[0]}(): An error was returned by TheTVDB when attempting to refresh a token."
+      return 1
+    fi
   fi
 
   if [[ -n "$token_json" ]]; then
     debug 'Using new token.'
     #Set the TVDB_TOKEN variable to the new token value.
     TVDB_TOKEN="$(jq -r '.token' <<< "$token_json")"
-
-    #Write the new token and the update time to a file.
-    jq --arg updated "$(date +%s)" '. + {updated: $updated}' <<< "$token_json" > "$m2kdir/tvdb_token.json"
+    if [[ -n "$TVDB_TOKEN" ]]; then
+      #Write the new token and the update time to a file.
+      jq --arg updated "$(date +%s)" '. + {updated: $updated}' <<< "$token_json" > "$m2kdir/tvdb_token.json"
+    else
+      err "${FUNCNAME[0]}(): Failed to retrieve a token from TheTVDB."
+      return 1
+    fi
   else
     debug 'Using existing token.'
     #Load our local, currently valid, token.
     TVDB_TOKEN="$(jq -r '.token' "$m2kdir/tvdb_token.json")"
   fi
-  ((LOGLEVEL>3)) && debug "TVDB_TOKEN: '$TVDB_TOKEN'."
+  ((LOGLEVEL > 3)) && debug "TVDB_TOKEN: '$TVDB_TOKEN'."
   return 0
 } #get_tvdb_token()
 
@@ -2700,6 +2713,7 @@ download_series_identification(){
 
   #Search TheTVDB and return an XML file with results
   inform "SEARCHING: www.TheTVDB.com for '$TITLE'"
+  ((LOGLEVEL > 3)) && debug "QUERY WAS: $curlGET \"https://api.thetvdb.com/search/series?name=$tvdbshowname\""
   series_query="$(eval "$curlGET \"https://api.thetvdb.com/search/series?name=$tvdbshowname\"")"
   #TODO: it is possible to search by zap2itID as well... so consider doing that too.
 
@@ -2740,11 +2754,16 @@ check_m2k_database_up_to_date(){
   local -i next_update=0
   local -i current_time=0
 
-  #Do not be so demanding for updates of series that have ended...
+  #Do not be so demanding for updates of series that have Ended...
   if [[ -f "$dbdir/$TVDB_TITLE.series_status.txt" ]]; then
-    debug 'The series has status="Ended", so extending the update period to about a month.'
-    debugcont "NOTE: you can force an update with \"myth2kodi --series-info '$TVDB_TITLE'\"."
-    [[ "$(<"$dbdir/$TVDB_TITLE.series_status.txt")" = 'Ended' ]] && UpdateDatabase=2419200
+    local series_status
+    series_status="$(<"$dbdir/$TVDB_TITLE.series_status.txt")"
+    debug "The series has status='$series_status'."
+    if [[ "${series_status,,}" = 'ended' ]]; then
+      debugcont 'So extending the update period to about a month.'
+      UpdateDatabase=2419200
+      debugcont "NOTE: you can force an update with \"myth2kodi --series-info '$TVDB_TITLE'\"."
+    fi
   fi
 
   #If file exist for last updated time, then get value
