Allows --commskip to scan a directory for already moved mpg files and regenerate their comskip files.

diff --git a/myth2kodi b/myth2kodi
--- a/myth2kodi
+++ b/myth2kodi
@@ -3475,16 +3475,47 @@ case "$InputPath" in
     #Err "The --commskip option is Not Implemented... yet."
     #eg: myth2kodi --commskip '/path/to/recordings/1070_20160331073100.mpg'
     InputPath="$2"
-    [[ ! -f "$InputPath" ]] && m2kHelp
-    Inform "Regenerating commskip file for $InputPath"
-    InputFileBasename="$(basename "$InputPath")"
-    GetMythTvPythonBindings
-    #TODO: Find the file that $InputPath points to or is pointed to by and use that for the move location below, otherwise we have to run full identification of Episode/etc.
-    [[ -L "$InputPath" ]] && movedrecordingname="$(readlink "$InputPath")"
-    #TODO: need to deal with link mode case, something like: movedrecordingname="$(find -L "$MoveDir/" -samefile "$InputPath")" #Actually, this form should work for both cases... with the problem that multiple links can be returned in link mode if there are multiple links...
-    ShowCommSkip="${movedrecordingname%.*}.txt"
-    mv "$m2kdir/markupframes.txt" "${ShowCommSkip}"
-    exit $?
+    [[ ! -f "$InputPath" && ! -d "$InputPath" ]] && m2kHelp
+    if [[ -f "$InputPath" && -L "$InputPath" ]]; then
+      Inform "Regenerating commskip file for $InputPath"
+      InputFileBasename="$(basename "$InputPath")"
+      GetMythTvPythonBindings
+      #TODO: Find the file that $InputPath points to or is pointed to by and use that for the move location below, otherwise we have to run full identification of Episode/etc.
+      #[[ -L "$InputPath" ]] && movedrecordingname="$(readlink "$InputPath")"
+      movedrecordingname="$(readlink "$InputPath")"
+      #TODO: need to deal with link mode case, something like: movedrecordingname="$(find -L "$MoveDir/" -samefile "$InputPath")" #Actually, this form should work for both cases... with the problem that multiple links can be returned in link mode if there are multiple links...
+      ShowCommSkip="${movedrecordingname%.*}.txt"
+      mv "$m2kdir/markupframes.txt" "${ShowCommSkip}"
+      exit $?
+    elif [[ -d "$InputPath" ]]; then
+      Warn "YOU ARE ABOUT TO SCAN THE DIRECTORY:"
+      WarnCont "$InputPath"
+      WarnCont "AND REGENERATE COMMSKIP FILES FOR ALL PREVIOUSLY MOVED RECORDINGS."
+      read -r -n1 -p "  Would you like myth2kodi to conduct a scan? y/(n)>" yesorno
+      printf '\n'
+      #Default to safety, ie do nothing.
+      [[ -z "$yesorno" ]] && yesorno="n"
+      if [ "$yesorno" = "y" ]; then
+        checkext="mpg" #TODO: Make this user/caller specifiable
+        scanpath="$InputPath"
+        Debug "Creating a temporary commskip_scan file: $m2kdir/commskip_scan.temp"
+        ls -1 "$scanpath"/*."$checkext" > "$m2kdir/commskip_scan.temp"
+        Inform "Scanning $scanpath for already moved $checkext files"
+        while read -r line ; do
+          Debug "Attempting to regenerate commskip file for $line"
+          [[ -f "$line" && -L "$line" ]] && myth2kodi --commskip "$line"
+        done < "$m2kdir/commskip_scan.temp"
+        Debug "Removing the temporary scan file: $m2kdir/commskip_scan.temp"
+        rm -f "$m2kdir/commskip_scan.temp"
+        exit 0
+      else
+        Warn "You must press 'y' to scan, aborting."
+        exit 0
+      fi
+    else
+      Err "The argument '$InputPath' is neither an already moved recording nor a directory to scan for them."
+      exit 1
+    fi
   ;;
 esac
 test "${InputTitle:0:1}" = "-" && m2kHelp
