Fixes for new TheTVDB-API(v2) code.
  + Fixes writing of tvdb_updates_list.json, it belongs in the
    main working directory, not a series-db directory.
  + Adds download and store of series-level information, such as:
    overview; status; first-aired; last-updated; and zap2itid.
    Some of these will be used for series-NFO, the status will be
    used as an additional mechanism for minimising unnecessary
    downloads from TheTVDB.
  + Bump between release version number to 1.4.2x.

diff --git a/myth2kodi b/myth2kodi
--- a/myth2kodi
+++ b/myth2kodi
@@ -673,7 +673,7 @@ m2k_init(){
   ((LOGLEVEL>=3)) && printf '%s\n' "Config complete." >> "$pre_logging_file"
 
   #What am I...
-  m2kVersion='myth2kodi Version 1.4.2w' ; declare -gr m2kVersion
+  m2kVersion='myth2kodi Version 1.4.2x' ; declare -gr m2kVersion
   m2kPlatform="$(uname)" ; declare -gr m2kPlatform
   ((LOGLEVEL>=3)) && printf '%s\n' "Running $m2kVersion on $m2kPlatform." >> "$pre_logging_file"
 
@@ -2630,6 +2630,7 @@ check_m2k_database_up_to_date(){
   #Return state = 1 means the local database should be updated from TheTVDB
   #Return state = 0 means the local database is up to date with TheTVDB
   local dbdir="$m2kdir/$TVDB_TITLE"
+  local tvdb_updates_list_file="$m2kdir/tvdb_updates_list.json"
   local -i next_update=0
   local -i current_time=0
 
@@ -2659,23 +2660,23 @@ check_m2k_database_up_to_date(){
     local updated_series updates_available list_last_updated
 
     #Find out when we last grabbed a list of recently updated series.
-    if [[ -f "$m2kdir/tvdb_updates_list.json" ]]; then
-      list_last_updated="$(jq -r .updated "$m2kdir/tvdb_updates_list.json")"
+    if [[ -f "$tvdb_updates_list_file" ]]; then
+      list_last_updated="$(jq -r .updated "$tvdb_updates_list_file")"
     else
-      debug "Seems we've never updated $TVDB_TITLE from TheTVDB -- no lastupdated.time file."
-      list_last_updated=42
+      debug "Seems we do not have an updates-list from TheTVDB."
+      list_last_updated=42 #A meaningless low number to start from...
     fi
 
     #Get a list of updated series.
     if (( (current_time - list_last_updated) < 3600 )); then
       #It has been less than an hour since we got a list so just use the local one.
-      updated_series="$(jq -r . "$m2kdir/tvdb_updates_list.json")"
+      updated_series="$(jq -r . "$tvdb_updates_list_file")"
     else
       #It has been longer than an hour so GET a new list of updated series.
       local curlGET="curl -s -m '$Timeout' -X GET -H 'Authorization: Bearer $TVDB_TOKEN' -H 'Accept: application/json'"
       local updates_site="https://api.thetvdb.com/updated/query?fromTime=$LastUpdatedTVDB"
       updated_series="$(eval "$curlGET '$updates_site'")"
-      jq --arg updated "$(date +%s)" '. + {updated: $updated}' <<< "$updated_series" > "$dbdir/tvdb_updates_list.json"
+      jq --arg updated "$(date +%s)" '. + {updated: $updated}' <<< "$updated_series" > "$tvdb_updates_list_file"
     fi
 
     updates_available="$(jq "contains({data: [{id: $TVDB_SERIESID}]})" <<< "$updated_series")"
@@ -2721,23 +2722,56 @@ prune_series_list(){
 download_series_info(){
   debug "ENTERING: ${FUNCNAME[0]}() ; CALLED FROM: ${FUNCNAME[1]}()"
   inform "Downloading Series: '$TVDB_SERIESID'"
+  local -i new_series_info=0
   local -i new_info_tvdb=0
   local -i new_info_tvmaze=0
   local -i ProcessingSuccesful=0
   local dbdir="$m2kdir/$TVDB_TITLE"
-  local tvdb_series_json="$dbdir/${TVDB_TITLE}_tvdb.json"
-  local tvmaze_series_json="$dbdir/${TVDB_TITLE}_tvmaze.json"
+  local tvdb_series_json="$dbdir/${TVDB_TITLE}_series_info.json"
+  local tvdb_episodes_json="$dbdir/${TVDB_TITLE}_tvdb.json"
+  local tvmaze_episodes_json="$dbdir/${TVDB_TITLE}_tvmaze.json"
   local curlGET="curl --silent -m '$Timeout' -X GET -H 'Authorization: Bearer $TVDB_TOKEN' -H 'Accept: application/json'"
   local series_data
   local page=1
   local -i tvmaze_id
   local -i episode_count
 
+  #First, grab the information for the series.
+  debug "Accessing the series-level information from TheTVDB for '$TVDB_SERIESID'."
+  series_data="$(eval "$curlGET 'https://api.thetvdb.com/series/$TVDB_SERIESID'")"
+  jq -r . <<< "$series_data" > "${tvdb_series_json}.temp"
+  if jq -e 'has("Error")' <<< "$series_data" > /dev/null; then
+    err "${FUNCNAME[0]}(): An error was returned by TheTVDB."
+    errcont "TVDB_SERIESID: '$TVDB_SERIESID'."
+    return 1
+  fi
+
+  #Check the new info is actually new, if there was no old info then it must be new.
+  if [[ -f "$tvdb_series_json" ]]; then
+    diff -q "${tvdb_series_json}.temp" "$tvdb_series_json" &> /dev/null
+    new_series_info="$?"
+  else
+    new_series_info=1
+  fi
+  if (( new_series_info == 1 )); then #NOTE: No-diff = 0; diff = 1; error = 2
+    [[ -f "$tvdb_series_json" ]] && mv "$tvdb_series_json" "$dbdir/${TODAY}_${TVDB_TITLE}_series_info.json"
+    mv "${tvdb_series_json}.temp" "$tvdb_series_json"
+    jq -r '.data.status'      "$tvdb_series_json" > "$dbdir/$TVDB_TITLE.series_status.txt"
+    jq -r '.data.overview'    "$tvdb_series_json" > "$dbdir/$TVDB_TITLE.series_overview.txt"
+    jq -r '.data.firstAired'  "$tvdb_series_json" > "$dbdir/$TVDB_TITLE.series_firstaired.txt"
+    jq -r '.data.lastUpdated' "$tvdb_series_json" > "$dbdir/$TVDB_TITLE.series_lastupdated.txt"
+    jq -r '.data.zap2itId'    "$tvdb_series_json" > "$dbdir/$TVDB_TITLE.series_zap2itid.txt"
+  elif (( new_series_info == 2 )); then
+    err "An error occurred while diff-ing: '${tvdb_series_json}.temp' and '$tvdb_series_json'."
+  elif (( new_series_info == 0 )); then
+    debug 'No new series-level information is available.'
+  fi
+
   #TODO: Should try to get jq to merge the pages rather than the manual hackery below.
   #Download the episode information from TheTVDB for TVDB_SERIESID
   debug "Accessing page '$page' of TheTVDB entry for '$TVDB_SERIESID'."
   series_data="$(eval "$curlGET 'https://api.thetvdb.com/series/$TVDB_SERIESID/episodes?page=$page'")"
-  jq -r '.data' <<< "$series_data" | sed 's/]$//' > "${tvdb_series_json}.temp"
+  jq -r '.data' <<< "$series_data" | sed 's/]$//' > "${tvdb_episodes_json}.temp"
   if jq -e 'has("Error")' <<< "$series_data" > /dev/null; then
     err "${FUNCNAME[0]}(): An error was returned by TheTVDB."
     errcont "TVDB_SERIESID: '$TVDB_SERIESID'."
@@ -2748,7 +2782,7 @@ download_series_info(){
   while [[ "$page" != 'null' ]]; do
     debug "Accessing page '$page' of TheTVDB entry for '$TVDB_SERIESID'."
     series_data="$(eval "$curlGET 'https://api.thetvdb.com/series/$TVDB_SERIESID/episodes?page=$page'")"
-    jq -r '.data' <<< "$series_data" | sed 's/^\[/,/' | sed 's/]$//'  >> "${tvdb_series_json}.temp"
+    jq -r '.data' <<< "$series_data" | sed 's/^\[/,/' | sed 's/]$//'  >> "${tvdb_episodes_json}.temp"
     if jq -e 'has("Error")' <<< "$series_data" > /dev/null; then
       err "${FUNCNAME[0]}(): An error was returned by TheTVDB."
       errcont "TVDB_SERIESID: '$TVDB_SERIESID'."
@@ -2757,21 +2791,21 @@ download_series_info(){
     fi
     page="$(jq .links.next <<< "$series_data")"
   done
-  printf ']\n' >> "${tvdb_series_json}.temp"
+  printf ']\n' >> "${tvdb_episodes_json}.temp"
 
   printf '%s\n' "$(date +%s)" > "$dbdir/lastupdated.time" && chmod 644 "$dbdir/lastupdated.time"
 
   #Check the new info is actually new, if there was no old info then it must be new.
-  if [[ -f "$tvdb_series_json" ]]; then
-    diff -q "${tvdb_series_json}.temp" "$tvdb_series_json" &> /dev/null
+  if [[ -f "$tvdb_episodes_json" ]]; then
+    diff -q "${tvdb_episodes_json}.temp" "$tvdb_episodes_json" &> /dev/null
     new_info_tvdb="$?" #NOTE: No-diff = 0; diff = 1; error = 2
   else
     new_info_tvdb=1
   fi
 
   if ((new_info_tvdb == 1)); then
-    [[ -f "$tvdb_series_json" ]] && mv "$tvdb_series_json" "$dbdir/${TODAY}_${TVDB_TITLE}_tvdb.json"
-    mv "${tvdb_series_json}.temp" "$tvdb_series_json"
+    [[ -f "$tvdb_episodes_json" ]] && mv "$tvdb_episodes_json" "$dbdir/${TODAY}_${TVDB_TITLE}_tvdb.json"
+    mv "${tvdb_episodes_json}.temp" "$tvdb_episodes_json"
   fi
 
   #Download the episode information from tvmaze for TVDB_SERIESID
@@ -2780,38 +2814,38 @@ download_series_info(){
     debug "Found matching tvmaze id: '$tvmaze_id'"
     local tvmaze_episodes_site="http://api.tvmaze.com/shows/$tvmaze_id/episodes"
     debug "Getting new tvmaze show info from: '$tvmaze_episodes_site'"
-    curl -L -s -m"$Timeout" "$tvmaze_episodes_site" > "${tvmaze_series_json}.temp"
+    curl -L -s -m"$Timeout" "$tvmaze_episodes_site" > "${tvmaze_episodes_json}.temp"
   fi
 
   #Check the new info is actually new, if there was no old info then it must be new.
-  if [[ -f "$tvmaze_series_json" ]]; then
-    diff -q "${tvmaze_series_json}.temp" "$tvmaze_series_json" &> /dev/null
+  if [[ -f "$tvmaze_episodes_json" ]]; then
+    diff -q "${tvmaze_episodes_json}.temp" "$tvmaze_episodes_json" &> /dev/null
     new_info_tvmaze="$?" #NOTE: No-diff = 0; diff = 1; error = 2
   else
     new_info_tvmaze=1
   fi
 
   if ((new_info_tvmaze == 1)); then
-    [[ -f "$tvmaze_series_json" ]] && mv "$tvmaze_series_json" "$dbdir/${TODAY}_${TVDB_TITLE}_tvmaze.json"
-    mv "${tvmaze_series_json}.temp" "$tvmaze_series_json"
+    [[ -f "$tvmaze_episodes_json" ]] && mv "$tvmaze_episodes_json" "$dbdir/${TODAY}_${TVDB_TITLE}_tvmaze.json"
+    mv "${tvmaze_episodes_json}.temp" "$tvmaze_episodes_json"
   fi
 
   if ((new_info_tvdb == 1)) || ((new_info_tvmaze == 1)); then
     inform "Downloaded new information for '$TVDB_TITLE'"
 
-    jq -r '.[] | .episodeName'        "$tvdb_series_json" > "$dbdir/$TVDB_TITLE.Ename.txt"
-    jq -r '.[] | .airedSeason'        "$tvdb_series_json" > "$dbdir/$TVDB_TITLE.S.txt"
-    jq -r '.[] | .airedEpisodeNumber' "$tvdb_series_json" > "$dbdir/$TVDB_TITLE.E.txt"
-    jq -r '.[] | .firstAired'         "$tvdb_series_json" > "$dbdir/$TVDB_TITLE.FAired.txt"
-    jq -r '.[] | .id'                 "$tvdb_series_json" > "$dbdir/$TVDB_TITLE.id.txt"
+    jq -r '.[] | .episodeName'        "$tvdb_episodes_json" > "$dbdir/$TVDB_TITLE.Ename.txt"
+    jq -r '.[] | .airedSeason'        "$tvdb_episodes_json" > "$dbdir/$TVDB_TITLE.S.txt"
+    jq -r '.[] | .airedEpisodeNumber' "$tvdb_episodes_json" > "$dbdir/$TVDB_TITLE.E.txt"
+    jq -r '.[] | .firstAired'         "$tvdb_episodes_json" > "$dbdir/$TVDB_TITLE.FAired.txt"
+    jq -r '.[] | .id'                 "$tvdb_episodes_json" > "$dbdir/$TVDB_TITLE.id.txt"
 
     [[ -f "$dbdir/$TVDB_TITLE.Plot.txt" ]] && rm -f "$dbdir/$TVDB_TITLE.Plot.txt"
 
-    episode_count="$(jq -r '.[] | .episodeName' "$tvdb_series_json" | wc -l)"
+    episode_count="$(jq -r '.[] | .episodeName' "$tvdb_episodes_json" | wc -l)"
     inform "Local-DB contains '$episode_count' entries from TheTVDB for '$TVDB_TITLE'."
     for i in $(seq 0 $((episode_count-1))); do
       {
-        jq -r ".[$i] | .overview" "$tvdb_series_json" \
+        jq -r ".[$i] | .overview" "$tvdb_episodes_json" \
           | tr -d "\n"                                \
           | sed -r 's/[^[:alnum:] &,.-]//g'           \
           | sed -r 's/^null$//'                       \
@@ -2821,18 +2855,18 @@ download_series_info(){
     done
 
     #If we also have a json file from tvmaze, then append that info
-    if [[ -f "$tvmaze_series_json" ]]; then
-      jq -r '.[] | .name'    "$tvmaze_series_json" >> "$dbdir/$TVDB_TITLE.Ename.txt"
-      jq -r '.[] | .season'  "$tvmaze_series_json" >> "$dbdir/$TVDB_TITLE.S.txt"
-      jq -r '.[] | .number'  "$tvmaze_series_json" >> "$dbdir/$TVDB_TITLE.E.txt"
-      jq -r '.[] | .airdate' "$tvmaze_series_json" >> "$dbdir/$TVDB_TITLE.FAired.txt"
-      jq -r '.[] | .id'      "$tvmaze_series_json" >> "$dbdir/$TVDB_TITLE.id.txt"
+    if [[ -f "$tvmaze_episodes_json" ]]; then
+      jq -r '.[] | .name'    "$tvmaze_episodes_json" >> "$dbdir/$TVDB_TITLE.Ename.txt"
+      jq -r '.[] | .season'  "$tvmaze_episodes_json" >> "$dbdir/$TVDB_TITLE.S.txt"
+      jq -r '.[] | .number'  "$tvmaze_episodes_json" >> "$dbdir/$TVDB_TITLE.E.txt"
+      jq -r '.[] | .airdate' "$tvmaze_episodes_json" >> "$dbdir/$TVDB_TITLE.FAired.txt"
+      jq -r '.[] | .id'      "$tvmaze_episodes_json" >> "$dbdir/$TVDB_TITLE.id.txt"
 
-      episode_count=$(jq -r '.[] | .name' "$tvmaze_series_json" | wc -l)
+      episode_count=$(jq -r '.[] | .name' "$tvmaze_episodes_json" | wc -l)
       inform "Local-DB contains '$episode_count' entries from tvmaze for '$TVDB_TITLE'."
       for i in $(seq 0 $((episode_count-1))); do
         {
-          jq -r ".[$i] | .summary" "$tvmaze_series_json" \
+          jq -r ".[$i] | .summary" "$tvmaze_episodes_json" \
             | tr -d "\n"                                 \
             | sed -r 's#</?p>##g'                        \
             | sed -r 's/[^[:alnum:] &,.-]//g'            \
